"""Abstract base class for trading strategies."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Optional
import logging

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    direction: str  # "buy", "sell", "neutral"
    confidence: float  # 0.0 to 1.0
    strategy: str
    legs: List[Dict]  # For multi-leg strategies like spreads
    metadata: Dict


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""
    
    def __init__(self, config: Dict):
        self.config = config
        self.name = self.__class__.__name__
        self.enabled = config.get("enabled", True)
    
    @abstractmethod
    def generate_signals(self, data: Dict) -> List[Signal]:
        """
        Generate trading signals based on market data.
        
        Args:
            data: Market data including prices, options chain, etc.
            
        Returns:
            List of Signal objects
        """
        pass
    
    @abstractmethod
    def calculate_position_size(self, account_value: float, 
                                signal: Signal) -> int:
        """
        Calculate appropriate position size.
        
        Args:
            account_value: Total account value
            signal: The trading signal
            
        Returns:
            Number of contracts/spreads to trade
        """
        pass
    
    def validate_signal(self, signal: Signal) -> bool:
        """Validate a signal meets strategy criteria."""
        if not self.enabled:
            logger.warning(f"Strategy {self.name} is disabled")
            return False
        
        if signal.confidence < 0.5:
            logger.warning(f"Signal confidence too low: {signal.confidence}")
            return False
        
        return True
    
    def get_required_data(self) -> List[str]:
        """Return list of required data fields."""
        return ["price", "options_chain"]
    
    def on_fill(self, order: Dict):
        """Callback when an order is filled."""
        logger.info(f"[{self.name}] Order filled: {order}")
    
    def on_exit(self, position: Dict, pnl: float):
        """Callback when a position is closed."""
        logger.info(f"[{self.name}] Position closed. P&L: ${pnl:.2f}")
